"""Rename Session to StreamlitSession

Revision ID: 3dd1baf2e6cd
Revises: 4b4bb9d37491
Create Date: 2025-05-17 12:26:06.094614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3dd1baf2e6cd'
down_revision: Union[str, None] = '4b4bb9d37491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("DROP TABLE session CASCADE")
    op.create_foreign_key(None, 'message', 'usersession', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_session_id_fkey', 'message', 'session', ['session_id'], ['id'])
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='session_pkey')
    )
    op.drop_table('usersession')
    # ### end Alembic commands ###
